#  Starter for Dockerized WP Instance
#     1) Replace 'wp_db' with unique database name
#     2) Replace 'wpsite' with unique arbitrary network name
#     3) Run docker-compose up -d
#     4) Uncomment PHPMyAdmin service & Run dc-up again

version: "3"

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # Arbitrary Database Name
      MYSQL_ROOT_DATABASE: wp_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    # Arbitrary Network Name
    networks:
      - wpsite
  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: root
  #   networks:
  #     - wpsite
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes: ["./:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    # Arbitrary Network Name
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
